export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CREATE_USER = 'CREATE_USER';
export const CREATE_NEW_DOCUMENT = 'CREATE_NEW_DOCUMENT';
export const VIEW_ALL_DOCUMENTS = 'VIEW_ALL_DOCUMENTS';
export const EDIT_DOCUMENT = 'EDIT_DOCUMENT';
export const DELETE_DOCUMENT = 'DELETE_DOCUMENT';
export const GET_USER_DOCUMENTS = 'GET_USER_DOCUMENTS';

